### PR TITLE
Fixes #4

### LINKED ISSUE #4: [Monitoring] Add new Grafana Panel with in/out Networking usage

### PR DESCRIPTION
**Pull request by dgpMakes**

### CODE REVIEW

**Comment by alvarolop** [comment]
This PR fixes #4 .

**Comment by alvarolop** [comment]
@dgpMakes Thanks for your contribution! . Could you move the Network panel to the bottom part of the Dashboard? To have all the Openshift related metrics together?
bitmojibitmoji

**Comment by dgpMakes** [comment]
Yep! The network panel now is under the OCP metrics and at the bottom :D

**Comment by alvarolop** [comment]
LGTM!!

**Review by alvarolop — APPROVED** [review]
LGTM

**Pull request merged**
